### ISSUE TITLE
What's with META proliferation?

### ISSUE THREAD

**Issue by zoffixznet** [skids/perl6sum#5]
Hey,

I was going through dists, renaming users' legacy META.info name to META6.json.

In your dist, I spot THREE meta files. How come you have these? Rakudo doesn't deal with YAML and META.info is a legacy name. Seems the only meta file that should exist is META6.json

**Comment by skids** [comment]
I use YAML to generate my META6.json.  I like YAML better.  Dists should be allowed to have build files as they see fit, IMO.  The META6.info is there because I went to META6.json before the ecosystem fully supported it, so I was maintaining both.

**Comment by zoffixznet** [comment]
Ah
